## created by @opbi/ncm
---
component:
  type: package
  name: ncm
  description: node config manager - create and update dotfiles made easy
  keywords: automation, dotfiles, dotenv, node, cli
  private: false
package:
  environment: cli
  npmScope: opbi
owner:
  type: organisation
  github: opbi
  team: product
  name: OPBI
  email: engineering@opbi.org
